version: 2.1
orbs:
  rust: circleci/rust@1.6.0
jobs:
  upload:
    docker:
      - image: cimg/base:stable
    steps:
      - store_artifacts:
          path: ~/target/release
workflows:
  example-workflow:
    jobs:
      - rust/lint-test-build:
          release: true
      - upload